### ISSUE TITLE
Geting this error even after updating the protobuf to 3.15.8 version. AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

### ISSUE THREAD

**Issue by SINHAPIYUSH** [Tauranis/deep_coffee#7]
Create tfrecords
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/app/deep_coffee/ml/images_to_tfrecords.py", line 2, in <module>
    from tensorflow_transform.beam.tft_beam_io import transform_fn_io, beam_metadata_io
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_transform/beam/__init__.py", line 18, in <module>
    from tensorflow_transform.beam import analyzer_impls
  File "/usr/local/lib/python3.6/dist-packages/tensorflow_transform/beam/analyzer_impls.py", line 26, in <module>
    import apache_beam as beam
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/__init__.py", line 98, in <module>
    from apache_beam import io
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/io/__init__.py", line 38, in <module>
    from apache_beam.io.gcp.pubsub import *
  File "/usr/local/lib/python3.6/dist-packages/apache_beam/io/gcp/pubsub.py", line 43, in <module>
    from google.cloud import pubsub
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub.py", line 20, in <module>
    from google.cloud.pubsub_v1 import PublisherClient
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub_v1/__init__.py", line 17, in <module>
    from google.cloud.pubsub_v1 import types
  File "/usr/local/lib/python3.6/dist-packages/google/cloud/pubsub_v1/types.py", line 19, in <module>
    from google.api import http_pb2
  File "/usr/local/lib/python3.6/dist-packages/google/api/http_pb2.py", line 35, in <module>
    create_key=_descriptor._internal_create_key,
AttributeError: module 'google.protobuf.descriptor' has no attribute '_internal_create_key'

**Comment by Tauranis** [comment]
I'm soooo sorry to respond this.
I've been out github due to personal issues.

It is overkill to use apache beam to transform this dataset into tfrecords since this is a small data problem.

Yes, the dataset was available in this repo. But it was hosted on my personal google drive and I had to erase it.
I'm sorry.

This code is pretty outdated. It was cool in 2018, but it is no longer in use.
